"""initial_schema

Revision ID: da44ab4aba2d
Revises: 0cf81de385f8
Create Date: 2026-04-18 16:26:45.470012+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da44ab4aba2d'
down_revision = '0cf81de385f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
