"""initial_schema

Revision ID: c564054e2c5f
Revises: da44ab4aba2d
Create Date: 2026-04-18 16:34:19.442285+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c564054e2c5f'
down_revision = 'da44ab4aba2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
