"""Alert ORM model — Clinical alert system."""

import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class AlertType(str, enum.Enum):
    """Categories of clinical alerts the system can generate.

    Attributes:
        HIGH_ANXIETY: Patient exhibits signs of high anxiety.
        HIGH_STRESS: Patient exhibits signs of sustained stress.
        CRITICAL_EMOTION: A critical negative emotion threshold was crossed.
        SUDDEN_SHIFT: A rapid, unexpected shift in dominant emotion occurred.
        MICROEXPRESSION_CLUSTER: Multiple microexpressions in a short window.
    """

    HIGH_ANXIETY = "high_anxiety"
    HIGH_STRESS = "high_stress"
    CRITICAL_EMOTION = "critical_emotion"
    SUDDEN_SHIFT = "sudden_shift"
    MICROEXPRESSION_CLUSTER = "microexpression_cluster"


class AlertSeverity(str, enum.Enum):
    """Severity levels for clinical alerts.

    Attributes:
        LOW: Informational; no immediate action required.
        MEDIUM: Warrants attention during post-session review.
        HIGH: Should be addressed before the session ends.
        CRITICAL: Requires immediate therapist intervention.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(Base):
    """Represents a clinical alert generated by the AI analysis engine.

    Alerts are created automatically when biometric thresholds are crossed.
    They can be acknowledged by the therapist to confirm the event was noted.

    Attributes:
        id: UUID primary key.
        session_id: The session during which the alert was triggered.
        patient_id: The patient this alert concerns.
        triggered_by_user_id: The system user or therapist who triggered it
            (NULL for system-generated alerts).
        alert_type: Category of the alert (see AlertType).
        severity: Urgency level (see AlertSeverity).
        message: Human-readable description of the alert.
        is_acknowledged: Whether a therapist has reviewed this alert.
        acknowledged_at: Timestamp of acknowledgement.
        acknowledged_by_id: The user who acknowledged the alert.
        created_at: When the alert was generated.
        session: The related session.
        patient: The related patient.
        acknowledged_by: The user who acknowledged the alert.
    """

    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    triggered_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    alert_type: Mapped[AlertType] = mapped_column(
        Enum(AlertType, name="alert_type"), nullable=False
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity, name="alert_severity"), nullable=False
    )
    message: Mapped[str] = mapped_column(Text, nullable=False)
    is_acknowledged: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    acknowledged_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )

    # Relationships
    session: Mapped["Session"] = relationship("Session", back_populates="alerts")  # noqa: F821
    patient: Mapped["Patient"] = relationship("Patient", back_populates="alerts")  # noqa: F821
    acknowledged_by: Mapped["User | None"] = relationship(  # noqa: F821
        "User", foreign_keys=[acknowledged_by_id]
    )

    def __repr__(self) -> str:
        return (
            f"<Alert type={self.alert_type.value!r} "
            f"severity={self.severity.value!r} ack={self.is_acknowledged}>"
        )
